spring.application.name=Banking_system


# Server
server.port=8080

# Database - MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/banking_system_proj?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Mohan@1819
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=ZmQ4ZDU0NDhhM2I5NjBkNjVjZGQ2MmGzNzM1ZGJkZmQ0YzdkOTYzZWZmZTY0YzZkZTJjZGI3ZWVhNTU2YmY3Mg==
app.jwt.expiration=86400000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=panjamohan1819@gmail.com	
spring.mail.password=xyej yauk kjnn dzsx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true